export const sounds=[
 ['ɑ̃','Atrium','🏛','nasal','an, en','enfant','Open ah, with air through the nose.'],['ɛ̃','Garden','🌿','nasal','in, ain, ein','pain','Open eh, with nasal airflow.'],['ɔ̃','Observatory','🔭','nasal','on','nom','Rounded lips and nasal airflow.'],['œ̃','Perfume shop','🧴','nasal','un','parfum','Rounded nasal vowel; often merges with /ɛ̃/.'],
 ['a','Beach','🏖','vowel','a, à','chat','Open mouth, as in ah.'],['ɑ','Theatre','🎭','vowel','â','pâte','Back ah; often merges with /a/.'],['i','Ice rink','⛸','vowel','i, y','lit','Tongue high and forward, lips unrounded.'],['y','Moon','🌙','vowel','u','lune','Say ee while rounding your lips.'],['u','Pool','🏊','vowel','ou','roue','Rounded oo, tongue toward the back.'],['e','Café','☕','vowel','é, -er, -ez','été','Pure closed eh; no English ay glide.'],['ɛ','Library','📚','vowel','è, ê, ai','lait','Open eh, as in bed.'],['o','Castle','🏰','vowel','eau, au, ô','eau','Rounded closed o; avoid a glide.'],['ɔ','Port','⚓','vowel','o','porte','More open rounded o.'],['ø','Fire station','🚒','vowel','eu','feu','Say closed eh with rounded lips.'],['œ','Flower shop','🌷','vowel','eu, œu','peur','Say open eh with rounded lips.'],['ə','Waiting room','🪑','vowel','e','le','Relaxed central vowel; may be dropped in speech.'],
 ['p','Pirate','🏴‍☠️','actor','p','pain','Unvoiced p, without a strong puff.'],['b','Bear','🐻','actor','b','beau','Voiced b.'],['t','Tiger','🐯','actor','t','tout','Tongue touches near the upper teeth.'],['d','Detective','🕵️','actor','d','deux','Voiced d near the upper teeth.'],['k','Cat','🐈','actor','c, qu, k','qui','Unvoiced k.'],['ɡ','Gorilla','🦍','actor','g, gu','gare','Hard voiced g.'],['g','Gorilla','🦍','actor','g, gu','gare','Hard voiced g; alternate IPA glyph.'],['f','Fairy','🧚','actor','f, ph','fou','Air between upper teeth and lower lip.'],['v','Vampire','🧛','actor','v','vous','Voiced f.'],['s','Snake','🐍','actor','s, ss, c, ç','sac','Unvoiced hiss.'],['z','Zebra','🦓','actor','z, s','zéro','Voiced s.'],['ʃ','Chef','👨‍🍳','actor','ch','chat','As in sh.'],['ʒ','Magician','🪄','actor','j, g','jour','As in the middle of vision.'],['m','Mime','🎭','actor','m','mot','Lips together, voiced through the nose.'],['n','Ninja','🥷','actor','n','nous','Tongue up, voiced through the nose.'],['ɲ','Onion knight','🧅','actor','gn','agneau','Palatal nasal, similar to Spanish ñ.'],['ŋ','Boxer','🥊','actor','ng','parking','Nasal at the back, as in sing.'],['l','Lion','🦁','actor','l','lit','Clear l with tongue near upper teeth.'],['ʁ','Robot','🤖','actor','r','rue','French r at the back of the mouth.'],['j','Yo-yo','🪀','glide','y, ill, i','yeux','Quick y glide, as in yes.'],['w','Wagon','🛒','glide','oi, ou','oui','Quick rounded w glide.'],['ɥ','Whistle','🪈','glide','u + vowel','huit','Glide from French /y/ into the next vowel.']
].map(([ipa,name,emoji,type,spelling,example,hint])=>({ipa,name,emoji,type,spelling,example,hint}));
export const chunks=[{ipa:'sjɔ̃',name:'Transformation machine',emoji:'⚙️',type:'chunk',hint:'A sound shortcut common in -tion words. It is not always a morpheme.'},{ipa:'mɑ̃',name:'Magic cloak',emoji:'🧥',type:'chunk',hint:'Common in -ment; often creates an adverb, but not always.'},{ipa:'aʒ',name:'Workshop',emoji:'🛠️',type:'chunk',hint:'Common in -age, often an action or result.'},{ipa:'ite',name:'Quality inspector',emoji:'🔎',type:'chunk',hint:'Common in -ité, often an abstract quality.'}];
export function tokenize(ipa,compact=true){const keys=[...(compact?chunks:[]),...sounds].sort((a,b)=>b.ipa.length-a.ipa.length);let rest=ipa.normalize('NFC').replace(/[ʼˈˌ.\s/()‿]/g,'');let out=[];while(rest){const key=keys.find(s=>rest.startsWith(s.ipa));if(key){out.push(key);rest=rest.slice(key.ipa.length)}else{out.push({ipa:[...rest][0],name:'Unmapped sound',emoji:'◌',type:'unknown'});rest=rest.slice([...rest][0].length)}}return out}
export function scene(w){const cues=tokenize(w.ipa);return `Picture ${cues.map(c=>c.type==='vowel'||c.type==='nasal'?`a scene at the ${c.name.toLowerCase()}`:c.name.toLowerCase()).join(' → ')}. In that exact order, make them act out “${w.meaning}”. ${w.article?.startsWith('la ')?'Add a silver ribbon to mark feminine gender.':w.article?.startsWith('le ')?'Add a golden key to mark masculine gender.':'If the article hides gender, check a dictionary before adding a gender prop.'}`}
export function schedule(previous,grade,now=Date.now()){const old=previous?.interval||0;const interval=grade==='again'?0:grade==='hard'?Math.max(1,Math.round(old*1.2)):grade==='good'?Math.max(1,Math.round(old*2.5)):Math.max(4,Math.round(old*3.5));return {interval,due:now+(grade==='again'?60000:interval*86400000),reviews:(previous?.reviews||0)+1,last:now};}
