import React,{useState,useEffect} from 'react';
import {createRoot} from 'react-dom/client';
import {BookOpen,Volume2,ArrowRight,Search,Layers,ChartNoAxesColumnIncreasing,Compass,Check,Download,Upload, X, Sparkles} from 'lucide-react';
import words from './words.json';
import {sounds,chunks,tokenize,scene,schedule} from './engine';
import './style.css';
const levels=['A1','A2','B1','B2','C1'];
function read(){try{return JSON.parse(localStorage.getItem('echo-progress'))||{cards:{},notes:{}}}catch{return {cards:{},notes:{}}}}
function App(){
 const [state,setState]=useState(read),[page,setPage]=useState('Learn'),[level,setLevel]=useState('A1'),[query,setQuery]=useState(''),[selected,setSelected]=useState(null),[revealed,setRevealed]=useState(false),[review,setReview]=useState(false),[notice,setNotice]=useState(''),[soundType,setSoundType]=useState('All'),[time,setTime]=useState(Date.now());
 useEffect(()=>{try{localStorage.setItem('echo-progress',JSON.stringify(state))}catch{setNotice('Browser storage is full or unavailable. Export your progress before leaving.')}},[state]);
 useEffect(()=>{const id=setInterval(()=>setTime(Date.now()),15000);return()=>clearInterval(id)},[]);
 const due=words.filter(w=>state.cards[w.id]?.due<=time), learned=Object.keys(state.cards).length;
 const pool=words.filter(w=>w.level===level), next=pool.find(w=>!state.cards[w.id]);
 const w=selected||next||pool[0];
 const say=(text)=>{if(!('speechSynthesis' in window)){setNotice('Speech is unavailable in this browser. Use the IPA guide.');return}const voices=speechSynthesis.getVoices();const voice=voices.find(v=>v.lang.startsWith('fr'));speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='fr-FR';u.rate=.8;if(voice)u.voice=voice;else setNotice('Using your device’s French speech service. Voice availability varies by browser.');speechSynthesis.speak(u)};
 const start=(word,isReview=false)=>{setSelected(word);setReview(isReview);setRevealed(!isReview);setPage('Learn')};
 const rate=(grade)=>{setState(s=>({...s,cards:{...s.cards,[w.id]:schedule(s.cards[w.id],grade)}}));setTime(Date.now());const following=review?due.find(x=>x.id!==w.id):pool.find(x=>x.id!==w.id&&!state.cards[x.id]);setSelected(following||null);setRevealed(!review);if(!following){setReview(false);setNotice(review?'You’re caught up. Come back when your next review is due.':'All words in this level have been introduced. Choose another level.');setPage('Progress')}};
 const exportData=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({version:1,...state})],{type:'application/json'}));a.download='echo-progress.json';a.click();URL.revokeObjectURL(a.href)};
 const importData=async(e)=>{try{const d=JSON.parse(await e.target.files[0].text());if(d.version!==1||!d.cards||!d.notes||typeof d.cards!=='object'||typeof d.notes!=='object'||Array.isArray(d.cards)||Array.isArray(d.notes))throw Error();for(const [id,c] of Object.entries(d.cards)){if(!words.some(w=>String(w.id)===id)||!Number.isFinite(c.due)||!Number.isFinite(c.interval)||c.interval<0||!Number.isFinite(c.reviews))throw Error()}for(const [id,n] of Object.entries(d.notes)){if(!words.some(w=>String(w.id)===id)||typeof n!=='string')throw Error()}setState({cards:d.cards,notes:d.notes});setNotice('Progress restored.')}catch{setNotice('That backup could not be read. Choose a valid Écho progress file.')}e.target.value=''};
 const progress=pool.filter(x=>state.cards[x.id]).length;
 return <div className="shell"><aside><a className="brand" href="#" onClick={e=>{e.preventDefault();setPage('Learn')}}>écho<span>FRENCH, IN YOUR MIND.</span></a><div className="nav-label">YOUR PRACTICE</div><nav>{[['Learn',BookOpen],['Vocabulary',Layers],['Sound atlas',Compass],['Progress',ChartNoAxesColumnIncreasing]].map(([name,Icon])=><button key={name} className={page===name?'active':''} onClick={()=>{setQuery('');setPage(name)}}><Icon size={19}/>{name}{name==='Learn'&&<span className="nav-dot"/>}</button>)}</nav><div className="sidebar-bottom"><div className="tiny-palace">é</div><strong>A little, every day.</strong><p>Build a world you can remember.</p><div className="local"><span/> Progress saved on this device</div></div></aside>
 <main><header><div><span className="eyebrow">YOUR SOUND PALACE</span><span className="header-divider">/</span>{page}</div><button className="review-pill" onClick={()=>due.length?start(due[0],true):setNotice('No reviews due yet. Learn a word to begin your review schedule.')}><span className="status-dot"/>{due.length} reviews due <ArrowRight size={15}/></button></header>
 {notice&&<div role="status" className="notice">{notice}<button aria-label="Dismiss notification" onClick={()=>setNotice('')}><X size={16}/></button></div>}
 {page==='Learn'&&<><div className="page-title"><div><div className="eyebrow">MAKE IT MEMORABLE</div><h1>A sound. A scene. A word.</h1><p>Turn French sounds into familiar faces and places.</p></div><div className="daily-count"><strong>{learned}</strong><span>words in your palace</span></div></div>
 <div className="level-bar"><div className="level-tabs">{levels.map(l=><button className={level===l?'chosen':''} key={l} onClick={()=>{setLevel(l);setSelected(null);setReview(false);setRevealed(false)}}>{l}<span>{({A1:'First steps',A2:'Everyday life',B1:'New horizons',B2:'Going deeper',C1:'Nuance'})[l]}</span></button>)}</div><span className="estimated">Estimated levels</span></div>
 <div className="learning-grid"><section className="word-card"><div className="card-top"><span className="tag">{w.level} · {review?'REVIEW':'DISCOVER'}</span><span>{w.pos} <span className="sep">/</span> #{w.id.toString().padStart(4,'0')}</span></div><div className="word-center"><span className="prompt">{review?'Recall the meaning and your scene':'MEET YOUR NEXT WORD'}</span><h2 lang="fr">{w.article||w.word}</h2><button className="pronunciation" onClick={()=>say(w.word)}><span>/{w.ipa}/</span><Volume2 size={19}/></button>{(!review||revealed)&&<h3>{w.meaning}</h3>}</div>
 {review&&!revealed?<div className="recall"><p>Say the meaning out loud. Can you reconstruct the sounds?</p><button className="primary" onClick={()=>setRevealed(true)}>Reveal meaning & scene <ArrowRight size={18}/></button></div>:<><div className="scene-panel"><div className="eyebrow"><Sparkles size={15}/> THE SOUND SCENE <span>GENERATED PROMPT</span></div><div className="cue-strip">{tokenize(w.ipa).map((s,i)=><React.Fragment key={i}>{i>0&&<span className="cue-arrow">→</span>}<button className={'cue '+s.type} onClick={()=>{setQuery(s.ipa);setPage('Sound atlas')}}><span>{s.emoji}</span><strong>{s.name}</strong><small>/{s.ipa}/</small></button></React.Fragment>)}</div><p>{state.notes[w.id]||scene(w)}</p><details><summary>Make this scene yours</summary><textarea aria-label="Your mnemonic" key={w.id} defaultValue={state.notes[w.id]||''} placeholder="Make the meaning concrete, exaggerated, and personal…" onBlur={e=>setState(s=>({...s,notes:{...s.notes,[w.id]:e.target.value}}))}/><small>Your scene saves when you leave this field.</small></details></div><div className="example"><button aria-label="Listen to example" onClick={()=>say(w.example)}><Volume2 size={18}/></button><div><p lang="fr">{w.example}</p><span>{w.translation}</span></div></div><div className="card-footer">{review?<><span>How well did you remember?</span><div className="rating">{['again','hard','good','easy'].map(g=><button onClick={()=>rate(g)} key={g}>{g}<small>{g==='again'?'1 min':schedule(state.cards[w.id],g).interval+' days'}</small></button>)}</div></>:<><span><Check size={16}/> Read it. Hear it. Picture it.</span><button className="primary" onClick={()=>rate('good')}>I’ve got it <ArrowRight size={18}/></button></>}</div></>}
 </section><div className="right-column"><section className="how-card"><span className="eyebrow">THE ÉCHO METHOD</span><h3>Give every sound<br/>a place to live.</h3><div className="method-step"><span>01</span><div><strong>Hear the word</strong><p>Start with pronunciation. Silent letters stay out of the scene.</p></div></div><div className="method-step"><span>02</span><div><strong>Meet your cast</strong><p>Consonants are characters. Vowels are places. Keep their order.</p></div></div><div className="method-step"><span>03</span><div><strong>Make something happen</strong><p>Let your cast act out the meaning. The stranger, the stickier.</p></div></div><button onClick={()=>{setQuery('');setPage('Sound atlas')}}>Explore the sound atlas <ArrowRight size={17}/></button></section><section className="journey-card"><div><span className="eyebrow">YOUR {level} JOURNEY</span><strong>{Math.round(progress/pool.length*100)}%</strong></div><div className="progress-track"><i style={{width:progress/pool.length*100+'%'}}/></div><p>{progress} of {pool.length.toLocaleString()} words introduced</p><span>One memorable scene at a time.</span></section><p className="subtle">Memory cues are invented associations, not etymology. Use the audio and IPA for the actual sounds.</p></div></div></>}
 {page==='Vocabulary'&&<><div className="page-title"><div className="eyebrow">THE COLLECTION</div><h1>5,500 doors into French.</h1><p>Explore your vocabulary, one sound scene at a time.</p></div><div className="filters"><label className="search"><Search size={18}/><input placeholder="Search French or English…" value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="Vocabulary level" value={level} onChange={e=>setLevel(e.target.value)}>{levels.map(l=><option key={l}>{l}</option>)}</select></div><p className="subtle">{pool.filter(w=>(w.word+' '+w.meaning).toLowerCase().includes(query.toLowerCase())).length} words · CEFR labels are source estimates.</p><div className="word-list">{pool.filter(w=>(w.word+' '+w.meaning).toLowerCase().includes(query.toLowerCase())).slice(0,150).map(w=><button key={w.id} onClick={()=>start(w)}><div><strong lang="fr">{w.article||w.word}</strong><span>/{w.ipa}/</span></div><div>{w.meaning}</div><span className="tag">{state.cards[w.id]?'Learning':w.level}</span><ArrowRight size={18}/></button>)}</div><p className="subtle">Showing up to 150 matches. Narrow your search to find more.</p></>}
 {page==='Sound atlas'&&<><div className="page-title"><div className="eyebrow">YOUR REUSABLE MEMORY ALPHABET</div><h1>The sound atlas.</h1><p>Learn the cast once. Reuse it in thousands of scenes.</p></div><div className="atlas-note"><strong>Follow the sound, from left to right.</strong><p>Characters act at vowel locations; glides move the scene. Nasal vowels have their own locations. Shortcuts compress recurring sound sequences, even when they are not morphemes. A golden key marks masculine nouns; a silver ribbon marks feminine nouns. Homophones share a cast, but act out different meanings.</p></div><div className="filters"><label className="search"><Search size={18}/><input placeholder="Search a sound, character, or spelling…" value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="Sound category" value={soundType} onChange={e=>setSoundType(e.target.value)}>{['All','actor','vowel','nasal','glide','chunk'].map(t=><option key={t}>{t}</option>)}</select></div><div className="sound-grid">{[...sounds,...chunks].filter(s=>(soundType==='All'||s.type===soundType)&&Object.values(s).join(' ').toLowerCase().includes(query.toLowerCase())).map(s=><article key={s.ipa}><div className="sound-heading"><span>{s.emoji}</span><strong>/{s.ipa}/</strong><small>{s.type==='actor'?'character':s.type==='chunk'?'shortcut':s.type}</small></div><h3>{s.name}</h3><p>{s.hint}</p>{s.example&&<button onClick={()=>say(s.example)}><Volume2 size={16}/>{s.example}<span>{s.spelling}</span></button>}</article>)}</div><p className="subtle">Representative France French. /ɑ/ and /a/, and /œ̃/ and /ɛ̃/, may merge by speaker. English descriptions are approximate; words may change in connected speech.</p></>}
 {page==='Progress'&&<><div className="page-title"><div className="eyebrow">SMALL STEPS, LASTING MEMORIES</div><h1>Your growing palace.</h1><p>Reviews return after 1 day, then grow with successful recall.</p></div><div className="stats"><article><strong>{learned}</strong><span>words introduced</span></article><article><strong>{due.length}</strong><span>ready for review</span></article><article><strong>{Object.values(state.cards).filter(c=>c.interval>=21).length}</strong><span>on intervals of 21+ days</span></article></div><button className="primary" disabled={!due.length} onClick={()=>start(due[0],true)}>Review due words <ArrowRight size={18}/></button><div className="level-progress">{levels.map(l=>{const total=words.filter(w=>w.level===l).length;const count=words.filter(w=>w.level===l&&state.cards[w.id]).length;return <article key={l}><strong>{l}</strong><div className="progress-track"><i style={{width:count/total*100+'%'}}/></div><span>{count} / {total}</span></article>})}</div><section className="backup"><h3>Keep your memories.</h3><p>Progress and personal scenes live in this browser. Export a backup to move devices or protect against cleared browser data. Import replaces your current progress.</p><button onClick={exportData}><Download size={17}/> Export progress</button><label className="import"><Upload size={17}/> Restore backup<input type="file" accept="application/json" onChange={importData}/></label></section><details className="sources"><summary>About the vocabulary & sources</summary><p>5,500 unique entries matched to IPA pronunciations. Translations, sentences, and CEFR estimates come from the AI-assisted <a href="https://github.com/vbvss199/Language-Learning-decks">Language-Learning-decks</a> dataset (MIT). Levels are estimates, not an official CEFR syllabus; vocabulary alone does not establish C1 proficiency. Content can contain errors. Pronunciations come from <a href="https://github.com/open-dict-data/ipa-dict">ipa-dict</a> (MIT); only the first listed pronunciation is used. Mnemonic scenes are generated templates, editable by you. This collection is not exhaustive and excludes entries without matching IPA.</p><p><a href="/licenses/LICENSE">Vocabulary license</a> · <a href="/licenses/IPA-LICENSE">IPA license</a> · <a href="/licenses/attributions.md">Frequency data attribution (CC BY-SA)</a></p></details></>}
 <footer><span>écho <i>·</i> Make French unforgettable.</span><button onClick={()=>setPage('Progress')}>Local progress & sources</button></footer></main></div>
}
createRoot(document.getElementById('root')).render(<App/>);
